graph BT
  be[Ballot Envelope]

  vc[Voter Certificate]
  vc-->be

  sk{{Voting Station Signing Keypair}}
  sk--public key-->vc
  sk-.private key.->sign1

  sign1((crypto_sign))
  sign1-->vc

  st[Voting Station Timestamp]
  st-->sign1

  box1((crypto_box))
  box1-->bb

  bb[Ballot Box]
  bb-->be

  bvh[Blinded Voter Hash]
  bvh-->sign1

  hash((crypto_hash))
  hash-->bvh

  va[Voter Attributes]
  va-->sign1

  sign2((crypto_sign))
  sign2-->box1

  vk{{Voter Signing Keypair}}
  vk--public key-->sign1
  vk-. private key .->sign2

  bc[Ballot Contents]
  bc-->sign2

  bt[Ballot Timestamp]
  bt-->sign2

  vh[Voter Hash]
  vh-->box1
  vh-->hash

  vhs[Voter Hash Secret]
  vhs-->box1
  vhs-->hash

  vid[Voter ID]
  vid-->scrypt

  scrypt((scrypt))
  scrypt-->vh

  tpk{{Tallying Authority Public Key}}
  tpk.->box1

  ek{{Ephemeral Keypair}}
  ek--public key-->be
  ek-. private key .->box1